#!/usr/bin/env python3
"""
Exemplar Selection (v2)
========================
Automatically selects key example conversations for the "same destination,
different journeys" narrative, using constraints to prevent exemplar drift.

Usage:
  python3 scripts/select_exemplars.py
"""

import json
import csv
import os
import statistics
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
CANONICAL_DIR = PROJECT_ROOT / "data" / "v2_unified" / "conversations"
EVIDENCE_CSV = PROJECT_ROOT / "data" / "v2_unified" / "evidence_features.csv"
OUTPUT = PROJECT_ROOT / "data" / "v2_unified" / "reports" / "exemplars.md"


def main():
    # Load evidence features
    evidence = {}
    with open(EVIDENCE_CSV) as f:
        for row in csv.DictReader(f):
            evidence[row['conv_id']] = row

    # Load canonical conversations
    convs = {}
    for fpath in sorted(CANONICAL_DIR.glob('*.json')):
        cid = fpath.stem
        with open(fpath) as f:
            data = json.load(f)
        convs[cid] = data

    print(f"Loaded {len(convs)} conversations, {len(evidence)} with evidence features")

    # Find Information-Seeker -> Expert-System conversations
    is_es_pairs = []
    for cid, data in convs.items():
        c = data.get('classification', {})
        if not c:
            continue
        hr = (c.get('humanRole') or {}).get('distribution', {})
        ar = (c.get('aiRole') or {}).get('distribution', {})
        if not hr or not ar:
            continue

        dominant_human = max(hr, key=hr.get)
        dominant_ai = max(ar, key=ar.get)

        if dominant_human == 'information-seeker' and dominant_ai == 'expert-system':
            msgs = data.get('messages', [])
            ev = evidence.get(cid, {})
            is_es_pairs.append({
                'conv_id': cid,
                'n_messages': len(msgs),
                'affect_variance': float(ev.get('affect_variance', 0)),
                'div_mean': float(ev.get('div_mean', 0)),
                'human_conf': hr.get('information-seeker', 0),
                'ai_conf': ar.get('expert-system', 0),
            })

    print(f"Information-Seeker -> Expert-System pairs: {len(is_es_pairs)}")

    # Filter to >= 6 messages
    long_enough = [p for p in is_es_pairs if p['n_messages'] >= 6]
    print(f"  With >=6 messages: {len(long_enough)}")

    if not long_enough:
        print("  WARNING: No IS->ES pairs with >=6 messages. Relaxing to >=4.")
        long_enough = [p for p in is_es_pairs if p['n_messages'] >= 4]

    by_variance = sorted(long_enough, key=lambda x: x['affect_variance'])

    smooth = by_variance[0] if by_variance else None
    volatile = by_variance[-1] if len(by_variance) > 1 else None

    # Director -> Expert-System for cross-role comparison
    dir_es_pairs = []
    for cid, data in convs.items():
        c = data.get('classification', {})
        if not c:
            continue
        hr = (c.get('humanRole') or {}).get('distribution', {})
        ar = (c.get('aiRole') or {}).get('distribution', {})
        if not hr or not ar:
            continue
        if max(hr, key=hr.get) == 'director' and max(ar, key=ar.get) == 'expert-system':
            ev = evidence.get(cid, {})
            dir_es_pairs.append({
                'conv_id': cid,
                'n_messages': len(data.get('messages', [])),
                'affect_variance': float(ev.get('affect_variance', 0)),
            })

    dir_volatile = max(dir_es_pairs, key=lambda x: x['affect_variance']) if dir_es_pairs else None

    # Write exemplars doc
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT, 'w') as f:
        f.write("# Selected Exemplars (v2 Unified)\n\n")
        f.write("*Auto-generated by `scripts/select_exemplars.py`*\n\n")
        f.write("## \"Same Destination, Different Journeys\" (IS -> ES)\n\n")

        if smooth:
            f.write(f"### Smooth: `{smooth['conv_id']}`\n")
            f.write(f"- Messages: {smooth['n_messages']}\n")
            f.write(f"- Affect variance: {smooth['affect_variance']:.6f}\n")
            f.write(f"- Divergence mean: {smooth['div_mean']:.4f}\n")
            f.write(f"- Role confidence: IS={smooth['human_conf']:.0%}, ES={smooth['ai_conf']:.0%}\n\n")

        if volatile:
            f.write(f"### Volatile: `{volatile['conv_id']}`\n")
            f.write(f"- Messages: {volatile['n_messages']}\n")
            f.write(f"- Affect variance: {volatile['affect_variance']:.6f}\n")
            f.write(f"- Divergence mean: {volatile['div_mean']:.4f}\n")
            f.write(f"- Role confidence: IS={volatile['human_conf']:.0%}, ES={volatile['ai_conf']:.0%}\n\n")

        if smooth and volatile:
            ratio = volatile['affect_variance'] / smooth['affect_variance'] if smooth['affect_variance'] > 0 else float('inf')
            f.write(f"### Variance Ratio: {ratio:.1f}x\n\n")

        if dir_volatile:
            f.write(f"## Cross-Role Comparison: Director -> ES\n\n")
            f.write(f"### Volatile Director: `{dir_volatile['conv_id']}`\n")
            f.write(f"- Messages: {dir_volatile['n_messages']}\n")
            f.write(f"- Affect variance: {dir_volatile['affect_variance']:.6f}\n\n")

    print(f"\nExemplars written to {OUTPUT}")
    if smooth:
        print(f"  Smooth: {smooth['conv_id']} (variance={smooth['affect_variance']:.6f})")
    if volatile:
        print(f"  Volatile: {volatile['conv_id']} (variance={volatile['affect_variance']:.6f})")
    if smooth and volatile:
        ratio = volatile['affect_variance'] / smooth['affect_variance'] if smooth['affect_variance'] > 0 else float('inf')
        print(f"  Ratio: {ratio:.1f}x")


if __name__ == '__main__':
    main()
